# fly.toml app configuration file generated for job-board-ui on 2023-11-19T11:40:17+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "job-board-ui"
primary_region = "otp"

[build]

[http_service]
  internal_port = 8043
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
